name: Build and publish to NuGet.org

on:
  push:
    branches:
      - "release/**"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 200
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0.302
          7.0.203
          7.0.202
          7.0.105
          6.0.408
          6.0.301
          6.0.300
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: cleanup
      run: dotnet build-server shutdown
    - name: Test
      run: dotnet test --no-build --no-restore --configuration Release --verbosity normal
    - name: Publish
      run: dotnet nuget push "MSBuild.CompilerCache/bin/Release/*.nupkg" --skip-duplicate --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json
